### ISSUE TITLE
Allow configuration of the autodiscover module name

### ISSUE THREAD

**Issue by andybak** [juanpex/django-model-report#76]
I am using another app that relies on reports.py autodiscovery. So either model_reports or my other app needs to allow this naming convention to be configurable. Ideally both of you :)

**Comment by juanpex** [comment]
I hope this solve the issue
https://github.com/juanpex/django-model-report/commit/6d2fa6175149eb95a1a9829ae3412f38dabb1a32

**Comment by andybak** [comment]
Wow that was quick. :) - I was going to propose a setting but this is a much better way to do it.

**Comment by juanpex** [comment]
;)
