### ISSUE TITLE
Template not found model_report/report.html 

### ISSUE THREAD

**Issue by mykljohn** [juanpex/django-model-report#77]
I've copied the model_report template folder and sub-folders to my template folder and it indicates it was found in the traceback-
any idea why?

**Comment by mykljohn** [comment]
Any help available for this problem?

**Comment by juanpex** [comment]
I don't understand what's the error.

"it was found in the traceback-" ???

**Comment by mykljohn** [comment]
Sorry, looking at my message, confused me as well.  I get the following error, but in the traceback it says it exists.  (several times because I copied it everywhere to try and resolve it)

TemplateDoesNotExist at /
model_report/report_list.html
Request Method: GET
Request URL:    http://xx.com/
Django Version: 1.8.6
Exception Type: TemplateDoesNotExist
Exception Value:  
model_report/report_list.html
Exception Location: /home/xx/.virtualenvs/django18/lib/python2.7/site-packages/django/template/loader.py in render_to_string, line 137
Python Executable:  /usr/local/bin/uwsgi
Python Version: 2.7.6
Python Path:  
['/var/www',
 '.',
 '',
 '/var/www',
 '/home/xx/.virtualenvs/django18/lib/python2.7',
 '/home/xx/.virtualenvs/django18/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/xx/.virtualenvs/django18/lib/python2.7/lib-tk',
 '/home/xx/.virtualenvs/django18/lib/python2.7/lib-old',
 '/home/xx/.virtualenvs/django18/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/xx/.virtualenvs/django18/local/lib/python2.7/site-packages',
 '/home/xx/.virtualenvs/django18/lib/python2.7/site-packages',
 '/home/xx/mysite']
Server time:    Sun, 15 May 2016 23:58:55 -0500
Template-loader postmortem

Django tried loading these templates, in this order:
Using loader django.template.loaders.filesystem.Loader:
/home/xx/mysite/templates/model_report/report_list.html (File does not exist)
/home/xx/mysite/myapp/templates/model_report/report_list.html (File exists)
Using loader django.template.loaders.app_directories.Loader:
/home/xx/.virtualenvs/django18/local/lib/python2.7/site-packages/grappelli/templates/model_report/report_list.html (File does not exist)
/home/xx/.virtualenvs/django18/lib/python2.7/site-packages/django/contrib/admin/templates/model_report/report_list.html (File does not exist)
/home/xx/.virtualenvs/django18/lib/python2.7/site-packages/django/contrib/admindocs/templates/model_report/report_list.html (File does not exist)
/home/xx/.virtualenvs/django18/lib/python2.7/site-packages/django/contrib/auth/templates/model_report/report_list.html (File does not exist)
/home/xx/.virtualenvs/django18/local/lib/python2.7/site-packages/django_spaghetti/templates/model_report/report_list.html (File does not exist)
/home/xx/.virtualenvs/django18/local/lib/python2.7/site-packages/django_tables2/templates/model_report/report_list.html (File does not exist)
/home/xx/mysite/eval/templates/model_report/report_list.html (File exists)
/home/xx/.virtualenvs/django18/local/lib/python2.7/site-packages/categories/editor/templates/model_report/report_list.html (File does not exist)
/home/xx/.virtualenvs/django18/local/lib/python2.7/site-packages/ckeditor/templates/model_report/report_list.html (File does not exist)
/home/xx/.virtualenvs/django18/lib/python2.7/site-packages/explorer/templates/model_report/report_list.html (File does not exist)
/home/xx/.virtualenvs/django18/local/lib/python2.7/site-packages/model_report/templates/model_report/report_list.html (File exists)

**Comment by juanpex** [comment]
this is weird

/home/xx/mysite/myapp/templates/model_report/report_list.html (**File exists**)
/home/xx/mysite/eval/templates/model_report/report_list.html (**File exists**)
/home/xx/.virtualenvs/django18/local/lib/python2.7/site-packages/model_report/templates/model_report/report_list.html (**File exists**)

I don't know if this app support django1.8
Maybe is that but this error is more basic than that.
Are you using some custom view?

**Comment by mykljohn** [comment]
no, i followed the instructions in the docs...created one report in report.py and got this error

**Comment by juanpex** [comment]
try to load the templates from a TemplateView only to know if that "hardcoded" view works.
I have no clue.

**Comment by mykljohn** [comment]
I found the problem with this, it was with the includes directory.  vague msg from python when part of a template is missing, it just sends notification of the main one.

Related issue, my buttons don't show up like on tghe example site not with the nice table....any idea?  I'm guessing it's to do with css, but I think I have the right css.

**Comment by mykljohn** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/11919990/16135003/483c1a1e-33e6-11e6-809f-97ffa6281a8a.png)

Also I'd like the date to print without the time, I found this in the doc...
model_report.utils.date_format(value, instance) 

so how would this work for 'evaluationdate'?

cheers

**Comment by juanpex** [comment]
For CSS check the path in urls for media.

If you like to format the value you can use this

def evaluationdate_format(value, instance):
    return value.strftime('YOURFORMAT')

override_field_formats = {
        'evaluationdate': evaluationdate_format,
    }

Regards,

**Comment by mykljohn** [comment]
Thanks Juan, this is looking awesome...though there's a few issues with the install...

Can I change the label of a field?  fore example I have the column 'user__user_id__username' which used the label Username, but I would like it to show "Evaluator" as it does on the form.

Also, I would like to select only those with status = 'Active'

I'm guessing I can use get_query_set()

**Comment by mykljohn** [comment]
FYI, I'm really not sure why, but I had to manually update some things after my pip install.

**Comment by juanpex** [comment]
Check the documentation or the example app :+1: 

https://github.com/juanpex/django-model-report/blob/master/example/test_project/app/reports.py

pip is unmantained, use the https url repo

**Comment by mykljohn** [comment]
I've checked through the doc and the example, but I can't figure out how to set the label.  I've tried this which I got from the example: 
override_field_labels = {'user__user_id__username' : 'Evaluator',}

but I get an error, string unexpected.

ahhh, just checked your link and there it is.  
def browser__name_label(report, field):
    return _("[Browser] Name")

cheers, again

**Comment by Priyankamsl** [comment]
HI,

I also experienced the same issue. I am new to Django. 
`TemplateDoesNotExist at /
base.html
Request Method:	GET
Request URL:	http://127.0.0.1:8000/
Django Version:	1.11
Exception Type:	TemplateDoesNotExist
Exception Value:	
base.html
Exception Location:	C:\Python27\lib\site-packages\django\template\engine.py in find_template, line 148
Python Executable:	C:\Python27\python.exe
Python Version:	2.7.12
Python Path:	
['C:\\Users\\MS\\pyctpr',
 'C:\\Python27\\lib\\site-packages\\requests-2.13.0-py2.7.egg',
 'C:\\Windows\\system32\\python27.zip',
 'C:\\Python27\\DLLs',
 'C:\\Python27\\lib',
 'C:\\Python27\\lib\\plat-win',
 'C:\\Python27\\lib\\lib-tk',
 'C:\\Python27',
 'C:\\Python27\\lib\\site-packages']
Server time:	Wed, 3 May 2017 07:00:38 +0000`
